# aws eks update-kubeconfig --region eu-west-2 --name epo-flask-app-eks
# k expose deploy flask-app-deploy --type=LoadBalancer --port=80 --target-port=9900

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app-deploy
  name: flask-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app-deploy
    spec:
      containers:
        - image: ghcr.io/emmanuelogiji/cloudboosta-flask-app:0.2.0
          name: cloudboosta-flask-app
          ports:
            - containerPort: 9900
          env:
            - name: AUTHOR
              value: Kubernetes
          startupProbe:
            httpGet:
              path: /author
              port: 9900
            failureThreshold: 30
            periodSeconds: 10
status: {}
